import json

data = {}
data['GST_SAMPLE_APP'] = []

data['GST_SAMPLE_APP'].append({
    # Provide all stream related parameters
	'DEFAULT_RETENTION_PERIOD_HOURS': 2,
	'DEFAULT_TIMECODE_SCALE_MILLISECONDS': 1,
    'DEFAULT_AVG_BANDWIDTH_BPS': 8388608,
    'DEFAULT_FRAGMENT_DURATION_MILLISECONDS': 2000,
    'DEFAULT_STORAGE_SIZE': 4 * 1024 * 1024,
    'DEFAULT_STREAM_FRAMERATE': 100,
    'DEFAULT_MAX_LATENCY_SECONDS': 40,
    'DEFAULT_BUFFER_DURATION_SECONDS': 120,
    'DEFAULT_REPLAY_DURATION_SECONDS': 40,
    'DEFAULT_CONNECTION_STALENESS_SECONDS': 60,

    # Provide all device related parameters
    'DEFAULT_DEVICE_STORAGE_TYPE': 'HYBRID_FILE', #Allowed values: MEMORY, HYBRID_FILE, CONTENT_STORE
    'DEFAULT_DEVICE_STORAGE_SIZE': 50 * 1024 * 1024
})

with open('param.json', 'w') as outfile:
    json.dump(data, outfile)



#define DEFAULT_CREDENTIAL_ROTATION_SECONDS 3600
#define DEFAULT_CREDENTIAL_EXPIRATION_SECONDS 180
#define DEFAULT_AUDIO_VIDEO_DRIFT_TIMEOUT_SECOND 5