#!/bin/bash
#
# Build the Kinesis Video Streams Producer GStreamer sink element
# Requires the producer SDK shared library is built already and available
# at the <sdk_source>/kinesis-video-native-build folder.
#
set -e

# --------- create required directories ---------------------------------------

KINESIS_VIDEO_ROOT=`pwd`

if [[ "$KINESIS_VIDEO_ROOT" == *\ * ]]; then
    echo "Current working path cannot have space in it !"
    exit
fi

DOWNLOADS="$KINESIS_VIDEO_ROOT/downloads"
if [ ! -d "$DOWNLOADS" ]; then
    mkdir -p "$DOWNLOADS"
fi

LIB_DESTINATION_FOLDER_PATH="$KINESIS_VIDEO_ROOT/downloads/local/lib"

# --------- Check if cmake version is applicable ------------------------------

CMAKE_VERSION_STRING=`cmake --version`
echo $CMAKE_VERSION_STRING
CMAKE_EXPECTED_MAJOR_VERSION=3
VERSION_ARRAY=( $CMAKE_VERSION_STRING )
CMAKE_VERSION=${VERSION_ARRAY[2]}
CMAKE_MAJOR_VERSION=${CMAKE_VERSION:0:1}

if [ "$CMAKE_MAJOR_VERSION" \< "$CMAKE_EXPECTED_MAJOR_VERSION" ]; then
  echo "CMake 3.x or higher is required.  You are running $CMAKE_VERSION"
  exit
fi

# -------- Check if libproducer.so or libproducer.dylib exists  ----------------
PLATFORM='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   PLATFORM='linux'
   LIB_FILE_EXTENSION=".so"
elif [[ "$unamestr" == 'Darwin' ]]; then
   PLATFORM='mac'
   LIB_FILE_EXTENSION=".dylib"
fi
if [ ! -f "libproducer$LIB_FILE_EXTENSION" ];then
	echo "*** Producer SDK library not found *** "
	echo "Build producer sdk using install-script before building the kvssink plugin using gstreamer-plugin-install-script"
	exit
fi


# --- Setting environment variables for cmake ---------------------------------
export PATH="$KINESIS_VIDEO_ROOT/downloads/local/bin:$PATH"
export CMAKE_PREFIX_PATH="$DOWNLOADS/local"

# gstreamer-plugin-install-script will be run from
# kinesis-video-native-build folder 
export KINESIS_VIDEO_STREAMS_PRODUCER_SDK_SOURCE_DIR=../
cd ../kinesis-video-gstreamer-plugin
cmake CMakeLists.txt
make gstkvssink
make kvs_producer_plugin_demo
make kvs_producer_plugin_rtsp_demo
make gstkvsplugintest

# copy the kvssink plugin into the library folder
cp libgstkvssink* "$LIB_DESTINATION_FOLDER_PATH"
# copy sample demo applications into kinesis-video-native-build folder
cp kvs_producer_plugin* "$KINESIS_VIDEO_ROOT"

# --- Environment variables in ~/.bashrc or ~/.bash_profile or ~/.zshrc -------
echo you may want to add the following environment variables 
echo in ~/.bashrc or ~/.bash_profile or ~/.zshrc 

export LD_LIBRARY_PATH="$KINESIS_VIDEO_ROOT/downloads/local/lib":$LD_LIBRARY_PATH
export PATH="$KINESIS_VIDEO_ROOT/downloads/local/bin":$PATH
export GST_PLUGIN_PATH="$KINESIS_VIDEO_ROOT/downloads/local/lib":$GST_PLUGIN_PATH

echo "**********************************************************"
echo Successful build of kinesis-video-gstreamer-plugin !!!
echo "**********************************************************"
