#!/bin/bash

set -e

# KINESIS_VIDEO_ROOT should point to kinesis-video-native-build directory
if [ -z $KINESIS_VIDEO_ROOT ]; then
  KINESIS_VIDEO_ROOT=`pwd`
fi

if [[ ! $KINESIS_VIDEO_ROOT =~ kinesis-video-native-build$ ]]; then
  echo "Please set KINESIS_VIDEO_ROOT environment variable to /path/to/kvssdk/kinesis-video-native-build or run the min-install-script inside kinesis-video-native-build directory"
  exit 1
fi

source $KINESIS_VIDEO_ROOT/install-script-common.sh

# --------- process args -----------------------------------------------------
max_parallel=2
build_type=Release
build_test=FALSE
build_gst_artifact=FALSE
build_jni_only=TRUE
build_producer=FALSE
env_var=""

setup

## --------- build kinesis video ----------------------------------------------
cd $KINESIS_VIDEO_ROOT
clean_up

if [[ "$PLATFORM" == 'mingw' ]]; then
  cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=${build_type} -DUSE_SYS_LIBRARIES=TRUE \
  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} -DBUILD_PRODUCER=${build_producer} \
  -DBUILD_JNI=${build_jni_only} \
  .
else
  cmake -DCMAKE_BUILD_TYPE=${build_type} -DUSE_SYS_LIBRARIES=TRUE \
  -DBUILD_TEST=${build_test} -DBUILD_GST_ARTIFACT=${build_gst_artifact} -DBUILD_PRODUCER=${build_producer} \
  -DBUILD_JNI=${build_jni_only} \
  .
fi

make -j ${max_parallel}

echo "**********************************************************"
echo Success!!!
echo "**********************************************************"
